language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: aN4mSodeJAW6NHbVXmyP5oU4FdfeXpu1XT4zEMaNrHRbcf84tErX1ph5eEuLOK2pUr1AGikdhguqX3kQjlX1tGHnLoLoAqag7ml/VQl+llcZV+OqMlEYml0YXKpy8t5C5SIzDw9e4D+JhQV9VTWVhIsE67b17Rxlh4OTEx+mfXQYXe1IfU1qSUL3t0Pz5faquMm3GQQCfjAxdRAL7oh0IA/ywbxB4ka5FA+kr22seYBOecFtwa10NHTCkgFtl7H3N556AbKvtQNA8YQgcYPqsVLy6kbjYF1fdkhryedLrc3kWrWmotWzO6iePg814kP3OLR2er0KhQGiS2Qs20G413CLhFQnIZVD04V/5O80pEhTPOtcQ+xQqnecI+If4JuEYQdDMnYkYBUjVCIpMmUiH7sDiSt2/h4xSy62/1Wi8gvjnUhu7rZu65zxTzb1eS6HHQVG4kMihrdQdZBeChf0mqpz359OG8WSbcQSbueKPR9wUNkPEGqxnvvq8fNsmCfjO2sz8+K4iy88ixE+WRPzhCNXpRBMO6gBsF5M+7r97qJwHFZr0AUI4SnYRmir6kjLDY2BuTl6E3Qhl6m0c1fHNb/LLUUx04ocmNZ9KX41P+VhvDg1qgRS/xTgXdYjffQ9QtqXdp/RosZoVX5mm0+X4oCiy73MDUhV4dQWoSYKY5o=
  app: bibliofile-rpd